targets:
  $default:
    builders:
      drift_dev:
        options:
          generate_connect_constructor: true
          scoped_dart_components: true
      freezed:
        options:
          map: true
          when: true
      json_serializable:
        options:
          explicit_to_json: true
